# Generated by Django 4.2.6 on 2023-11-22 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_pic',
            name='profile',
            field=models.ImageField(default='', upload_to='profile'),
        ),
    ]
