# Generated by Django 4.2.6 on 2024-01-02 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_alter_profile_pic_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='email',
            field=models.EmailField(max_length=20, unique=True),
        ),
    ]
