# Generated by Django 4.2.6 on 2025-02-24 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_alter_data_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='email',
            field=models.EmailField(default='', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='message',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='data',
            name='name',
            field=models.CharField(default='', max_length=20, unique=True),
        ),
    ]
